global_costmap:

  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 4.0
  publish_frequncy: 2.0
  static_map: false
  rolling_window: true
  width: 15.0
  height: 15.0
  resolution: 0.05
  origin_x: 0.0
  origin_y: 0.0
