obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[0.175, 0.175], [-0.175, 0.175], [-0.175, -0.175], [0.175, -0.175]]
#robot_radius: ir_of_robot
inflation_radius: 0.5

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: /base_laser_link, data_type: LaserScan, topic: /scan_laser, marking: true, clearing: true}
